---
title: "Introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(soilspec.format)
```

# Read a soil spectroscopy file given only a path
```
> path <- asd.binary.file.path()

> result <- read.soilspec(path)

> names(result)
 [1] "status"                  "mode"                    "is.absorbance"           "is.reflectance"          "is.transmittance"       
 [6] "is.descending"           "origin"                  "type"                    "data"                    "standardised.metadata"  
[11] "all.instrument.metadata"   

> result$status
[1] 0

> result$is.descending
[1] FALSE

> result$is.reflectance
[1] TRUE

> result$mode
[1] "reflectance"

> head(result$data)
  wavenumber  intensity
1        350 0.05432920
2        351 0.04792801
3        352 0.05130503
4        353 0.05339854
5        354 0.04970677
6        355 0.05435767

> plot(result$data, type="l")

> result$standardised.metadata
$sample_id
[1] ""

$spectra_id
[1] ""

$spectra_source_file_name
[1] "example.asd"

$date_time
[1] "2017-06-21 10:33:49 ACST"

$response
[1] "reflectance"

$instrument_technology_type
[1] "visNIR"

$instrument_manufacturer
[1] "ASD"

$instrument
[1] "FieldSpec FR"

...

$bulb
[1] 0

$swir1_gain
[1] 569

$swir2_gain
[1] 1160

$swir1_offset
[1] 2180

$swir2_offset
[1] 2415

$splice1_wavelength
[1] 1000

$splice2_wavelength
[1] 1830

> result$all.instrument.metadata
$co
[1] "as7"

$comments
[1] ""

$when
[1] "2017-06-20 19:04:47 ACST"

$program_version
[1] "6.0"

$file_version
[1] "7.0"

$dc_corr
[1] TRUE
...
```
