// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// parse_nicolet_spa
List parse_nicolet_spa(const char* filename);
RcppExport SEXP _soilspec_format_parse_nicolet_spa(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_nicolet_spa(filename));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_soilspec_format_parse_nicolet_spa", (DL_FUNC) &_soilspec_format_parse_nicolet_spa, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_soilspec_format(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
